### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vladimir-eremin** [danyangz/Slim#4]
Hi,

I am facing a segmentation fault error when trying to run Slim on Centos 7.5 with Docker 19.03.6.

Below is some output from my debug effort with gdb:

> $ docker run --cap-add=SYS_PTRACE --name c1 -v /tmp/slim/:/slim -it pingpong:v1
> [root@c1 socket]# gdb --args env LD_PRELOAD=/slim/socket/SlimSocket.so iperf3 -s
> (gdb) run
> Starting program: /usr/bin/env LD_PRELOAD=/slim/socket/SlimSocket.so iperf3 -s
> warning: Error disabling address space randomization: Operation not permitted
> process 115 is executing new program: /usr/bin/iperf3
> WARNING: VNET_PREFIX is not set. Using 0.0.0.0/0.
> All connections are treated as virtual network connections.
> [TRACE] New client with sock 4.
> [TRACE] result of pthread_create --> 0
> [TRACE] Start to handle the request from client sock 4.
> [TRACE] Start to read from sock 4
> [TRACE] Get request cmd 0
> [DEBUG] SOCKET_SOCKET
> [TRACE] write rsp 4 bytes to sock 4
> 
> Program received signal SIGSEGV, Segmentation fault.
> fd_store (type=fd_fsocket, host_fd=10, overlay_fd=-1, app_fd=-1) at socket.c:116
> 116             fdi->host_fd = host_fd;
> (gdb) bt
> #0  fd_store (type=fd_fsocket, host_fd=10, overlay_fd=-1, app_fd=-1) at socket.c:116
> #1  socket (domain=<optimized out>, type=type@entry=1, protocol=protocol@entry=0) at socket.c:507
> #2  0x00007ffff78cb640 in netannounce (domain=0, proto=proto@entry=1, local=0x0, port=<optimized out>) at net.c:158
> #3  0x00007ffff78c7b5e in iperf_server_listen (test=test@entry=0x603010) at iperf_server_api.c:75
> #4  0x00007ffff78c8372 in iperf_run_server (test=test@entry=0x603010) at iperf_server_api.c:469
> #5  0x0000000000400f3b in run (test=test@entry=0x603010) at main.c:152
> #6  0x0000000000400d29 in main (argc=2, argv=0x7fffffffe778) at main.c:111

Would be glad to hear some ideas on how to resolve the issue.

Thanks,
Vladimir

**Comment by vladimir-eremin** [comment]
Issue resolved: IPv6 has to be enabled by changing the corresponding kernel boot option into ipv6.disable=0
